/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0/userguide/multi_project_builds.html
 */

rootProject.name = "application-layer"
include("rest")

val externalProjectsPaths = mapOf(
    "../domain-layer" to listOf(
        "tn.ksoftwares.hexagonal:core" to ":core"
    )
)

@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    externalProjectsPaths.filter { File(it.key).exists() }
        .forEach {
            includeBuild(it.key) {
                dependencySubstitution {
                    it.value.forEach { sub ->
                        substitute(module(sub.first)).using(project(sub.second))
                    }
                }
            }
        }
}

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenLocal()
    }

    listOf("../plugins").filter { File(it).exists() }
        .forEach {
            includeBuild(it)
        }
}
